# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YQHPicTxtUIDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YQHPicTxtUIDemo

 pod 'Masonry', '~> 1.1.0'
 pod 'SDWebImage','~> 5.0'
 pod 'YYText'
 pod 'YQHPicTxtUI', :path => '/Users/yangchiher/github/YQHPicTxtUI/' #图文混排

end
